stages:
  - install
  - build
  - test
  - versions

variables:
  IMAGE: ubuntu:latest

install_packages:
  stage: install
  image: $IMAGE
  script:
    - apt update -y
    - apt install -y curl gpg git build-essential
    - curl https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc | gpg --dearmor > conda.gpg
    - install -o root -g root -m 644 conda.gpg /usr/share/keyrings/conda-archive-keyring.gpg
    - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/conda-archive-keyring.gpg] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main" > /etc/apt/sources.list.d/conda.list
    - apt update -y
    - apt install -y conda

checkout_and_build:
  stage: build
  image: $IMAGE
  script:
    - git config --global --add safe.directory /__w/virtual-accelerator/virtual-accelerator
    - .gitlab/workflows/conda-build.sh

corrector_test:
  stage: test
  image: $IMAGE
  script:
    - ./.gitlab/corrector-test.sh

previous_pvs_test:
  stage: test
  image: $IMAGE
  script:
    - ./.gitlab/pv-test.sh

print_versions:
  stage: versions
  image: $IMAGE
  script:
    - ./.gitlab/conda-versions.sh
