name: build-virac

on:
  push:
    tags:
      - '*'
    branches:
      - '*'

jobs:


  centos-stream:
    runs-on: ubuntu-latest
    steps:

      - name: Install packages
        run: |
          brew reinstall pkg-config fftw

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          .github/workflows/pip-build.sh

      - name: Test
        run: |
          .github/workflows/pip-tests.sh

      - name: Print Versions
        run: |
          .github/workflows/pip-versions.sh      
