name: build-virac

on:
  push:
    tags:
      - '*'
    branches:
      - '*'

jobs:


  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
         - name: Install Conda
           run: |
             apt update -y
             apt install -y curl gpg git build-essential
             curl https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc | gpg --dearmor > conda.gpg
             install -o root -g root -m 644 conda.gpg /usr/share/keyrings/conda-archive-keyring.gpg
             echo "deb [arch=amd64 signed-by=/usr/share/keyrings/conda-archive-keyring.gpg] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main" > /etc/apt/sources.list.d/conda.list
             apt update -y
             apt install -y conda

         - uses: actions/checkout@v4
           with:
            fetch-depth: 0

         - name: Build
           run: |
             git config --global --add safe.directory /__w/virtual-accelerator/virtual-accelerator
             .github/workflows/conda-build.sh

         - name: Corrector Test
           run: |
             .github/workflows/corrector-test.sh

         - name: Previous PVs Test
           run: |
             .github/workflows/pv-test.sh

         - name: Print Versions
           run: |
             .github/workflows/conda-versions.sh  
